<script setup>
</script>
<template>
    <LayoutNavModuleGroup
        v-if="useCheckAccessibility([
            AccessibilityTypes.ACCOUNTING_GROUP,
        ])"
        title="Accounting"
    >
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_JOURNAL_ENTRY,
            ])"
            linkarea="/accounting/journal-entry"
            icon="iconoir:plug-type-l"
            single-nav-title="Journal Entry"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_SETUP_CHART_OF_ACCOUNTS,
            ])"
            linkarea="/accounting/chart-of-accounts"
            icon="ci:table"
            single-nav-title="Chart of Accounts"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_REQUEST_GROUP
            ])"
            icon="iconoir:bell-notification"
            title="Requests"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_REQUEST_NON_PURCHASE_ORDER_GROUP
                ])"
                linkarea="/accounting/request/non-purchase-order"
                icon="iconoir:credit-card-2"
                single-nav-title="Non-purchase Order"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_REQUEST_GROUP,
                ])"
                linkarea="/accounting/request/purchase-order"
                icon="iconoir:credit-card-2"
                single-nav-title="Purchase Order"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_REQUEST_PRE_PAYROLL_AUDIT,
                ])"
                linkarea="/accounting/request/payroll-request"
                icon="iconoir:credit-card-2"
                single-nav-title="Payroll"
            />
        </LayoutNavGroup>
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_VOUCHER_DISBURSEMENT_GROUP,
            ])"
            icon="iconoir:credit-cards"
            title="Vouchers"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_VOUCHER_DISBURSEMENT_GROUP
                ])"
                linkarea="/accounting/voucher/disbursement"
                icon="iconoir:hand-contactless"
                single-nav-title="Disbursement Voucher"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_VOUCHER_CASH_GROUP
                ])"
                linkarea="/accounting/voucher/cash"
                icon="iconoir:iconoir:cash"
                single-nav-title="Cash Voucher"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_REPORTS_GROUP,
            ])"
            linkarea="/accounting/reports"
            icon="oui:app-reporting"
            single-nav-title="Reports"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.ACCOUNTING_SETUP_GROUP,
            ])"
            icon="iconoir:credit-cards"
            title="Setup"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_APPROVALS,
                ])"
                linkarea="/accounting/setup/approvals"
                icon="iconoir:thumbs-up"
                single-nav-title="Approvals"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_ACCOUNT_TYPES,
                ])"
                linkarea="/accounting/setup/account"
                icon="ion:ios-paper-outline"
                single-nav-title="Account"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_ACCOUNT_TYPES,
                ])"
                linkarea="/accounting/setup/account-type"
                icon="ion:ios-today"
                single-nav-title="Account Type"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_BOOK_OF_ACCOUNTS,
                ])"
                linkarea="/accounting/setup/books"
                icon="iconoir:book"
                single-nav-title="Book of Accounts"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_ACCOUNT_GROUPS,
                ])"
                linkarea="/accounting/setup/account-groups"
                icon="iconoir:commodity"
                single-nav-title="Account Group"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_PARTICULAR_GROUP,
                ])"
                linkarea="/accounting/setup/particular-groups"
                icon="iconoir:drone"
                single-nav-title="Particular Group"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_POSTING_PERIODS,
                ])"
                linkarea="/accounting/setup/posting-period"
                icon="iconoir:notes"
                single-nav-title="Posting Period"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_STAKEHOLDERS,
                ])"
                linkarea="/accounting/setup/stakeholder"
                icon="iconoir:user-square"
                single-nav-title="Payees"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_SYNCHRONIZATION,
                ])"
                linkarea="/accounting/synchronization"
                icon="iconoir:refresh-double"
                single-nav-title="API Synchronization"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_TERMS,
                ])"
                linkarea="/accounting/setup/terms"
                icon="iconoir:database-script-minus"
                single-nav-title="Terms"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.ACCOUNTING_SETUP_WITHHOLDING_TAX,
                ])"
                linkarea="/accounting/setup/withholding"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Withholding Tax"
            />
            <LayoutNavSingle
                linkarea="/accounting/setup/transactionFlowSetup"
                icon="iconoir:database-script-minus"
                single-nav-title="Transaction Flow Setup"
            />
        </LayoutNavGroup>
    </LayoutNavModuleGroup>
</template>
