<script setup>
const config = useRuntimeConfig()
</script>
<template>
    <LayoutNavModuleGroup
        v-if="useCheckAccessibility([
            AccessibilityTypes.hrms_group
        ])"
        title="hrms"
    >
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_dashboard,
            ])"
            linkarea="/hrms"
            icon="ic:round-dashboard"
            single-nav-title="HRMS Dashboard"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_announcement,
            ])"
            linkarea="/hrms/announcement"
            icon="ic:outline-announcement"
            single-nav-title="Announcement"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_attendance_group,
            ])"
            icon="ic:outline-punch-clock"
            title="Attendance"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_attendance_portal,
                ])"
                linkarea="/hrms/attendance/portal"
                icon="ic:baseline-web"
                single-nav-title="Attendance Portal"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_attendance_logs,
                ])"
                linkarea="/hrms/attendance/logs"
                icon="ic:baseline-book"
                single-nav-title="Attendance Logs"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_dtr,
                ])"
                linkarea="/hrms/attendance/dtr-v2"
                icon="material-symbols:alarm-on-outline-rounded"
                single-nav-title="Daily Time Record"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_failure_to_log,
                ])"
                linkarea="/hrms/attendance/failtolog"
                icon="ic:baseline-flag-circle"
                single-nav-title="Failure To Log"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_face_recognition,
                ])"
                linkarea="/hrms/attendance/facerecognition"
                icon="mdi:face-recognition"
                single-nav-title="Face Recognition"
            />
            <LayoutNavSingle
                v-show="useBetaOnly()"
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_attendance_login,
                ])"
                linkarea="/hrms/attendance/attendancelogin"
                icon="material-symbols:person-add-outline-rounded"
                single-nav-title="Attendance Login"
            />
            <LayoutNavSingle
                v-show="useBetaOnly()"
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_qr_generator,
                ])"
                linkarea="/hrms/attendance/qr-generate"
                icon="material-symbols:qr-code-scanner-rounded"
                single-nav-title="Generate QR Code"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_attendance_qr_login,
                ])"
                linkarea="/hrms/attendance/qr-login"
                icon="material-symbols:qr-code-scanner-rounded"
                single-nav-title="Attendance QR"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_event_calendar,
            ])"
            linkarea="/hrms/calendar"
            icon="ic:round-calendar-month"
            single-nav-title="Event Calendar"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_employee_group,
            ])"
            icon="ic:baseline-people-outline"
            title="Employee"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_employee_201_group
                ])"
                linkarea="/hrms/employee/201"
                icon="ic:round-folder-shared"
                single-nav-title="201"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_employee_pan_group,
                ])"
                linkarea="/hrms/employee/paf"
                icon="ic:round-add-card"
                single-nav-title="Personnel Action Notice"
            />
            <LayoutNavSingle
                v-show="useBetaOnly()"
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_employee_onboarding,
                ])"
                linkarea="/hrms/employee/onboarding"
                icon="ic:round-assignment-ind"
                single-nav-title="Onboarding"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_employee_job_applicant,
                ])"
                linkarea="/hrms/employee/applicant"
                icon="ic:baseline-diversity-3"
                single-nav-title="Job Applicants"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_employee_manpowerrequest_group,
                ])"
                linkarea="/hrms/employee/manpower"
                icon="ic:round-people-alt"
                single-nav-title="Manpower Request"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.HRMS_LOCATION_EMPLOYEES,
            ])"
            linkarea="/hrms/work-locations"
            icon="material-symbols:construction"
            single-nav-title="Employee Work Locations"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_loans_and_advances_group,
            ])"
            icon="mdi:cash"
            title="Loans and Advances"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_loans_and_advances_cash_advance_group,
                ])"
                linkarea="/hrms/loans/cashadvance"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Cash Advances"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.HRMS_LOANSANDADVANCES_LOANS_GROUP,
                ])"
                linkarea="/hrms/loans"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Loans"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_loans_and_advances_other_deductions,
                ])"
                linkarea="/hrms/loans/otherdeductions"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Other Deductions"
            />
        </LayoutNavGroup>
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_lnotnto_group,
            ])"
            icon="mdi:account-clock"
            title="Leaves and Overtime"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_lnotnto_leave_group,
                ])"
                linkarea="/hrms/leave"
                icon="fluent-mdl2:leave-user"
                single-nav-title="Leave"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_lnotnto_overtime_group,
                ])"
                linkarea="/hrms/overtime"
                icon="mingcute:time-line"
                single-nav-title="Overtime"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_lnotnto_travel_order_group,
                ])"
                linkarea="/hrms/travelorder"
                icon="material-symbols:googler-travel"
                single-nav-title="Travel Order"
            />
        </LayoutNavGroup>
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_payroll_group,
            ])"
            icon="ion:ios-people"
            title="Payroll"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_payroll_salary_group,
                ])"
                linkarea="/hrms/payroll/salary"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Salary"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_payroll_salarydisbursement_group,
                ])"
                linkarea="/hrms/payroll/salary-disbursement"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Salary Disbursement"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.HRMS_PAYROLL_13THMONTH_GROUP,
                ])"
                linkarea="/hrms/payroll/13thmonthpay"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="13th Month Pay"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_payroll_allowance,
                ])"
                linkarea="/hrms/payroll/allowance"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Allowance"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.HRMS_REQUEST_VOID_GROUP,
            ])"
            linkarea="/hrms/requests/void"
            icon="mdi:archive-cancel"
            single-nav-title="Void Requests"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_reports_group,
            ])"
            linkarea="/hrms/reports"
            icon="ic:sharp-add-chart"
            single-nav-title="Reports"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_schedule_group,
            ])"
            icon="uim:schedule"
            title="Schedule"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_schedule_department,
                ])"
                linkarea="/hrms/schedule/department"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Department Schedule"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_schedule_employee,
                ])"
                linkarea="/hrms/schedule/employee"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Employee Schedule"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_schedule_project,
                ])"
                linkarea="/hrms/schedule/project"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Project Schedule"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_hmo,
            ])"
            linkarea="/hrms/hmo"
            icon="ic:baseline-health-and-safety"
            single-nav-title="HMO"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.hrms_setup_group
            ])"
            icon="ion:ios-people"
            title="Setup"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_user_account,
                ])"
                linkarea="/hrms/setup/useraccounts"
                icon="ic:round-manage-accounts"
                single-nav-title="User Accounts"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_approvals,
                ])"
                linkarea="/hrms/setup/approvals"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Approvals"
            />
            <LayoutNavSingle
                v-show="useBetaOnly() && false"
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_division,
                ])"
                linkarea="/hrms/setup/division"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Division"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_department,
                ])"
                linkarea="/hrms/setup/department"
                icon="ic:round-meeting-room"
                single-nav-title="Department"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_position,
                ])"
                linkarea="/hrms/setup/position"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Position"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_allowance,
                ])"
                linkarea="/hrms/setup/allowance"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Allowance"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_leaves,
                ])"
                linkarea="/hrms/setup/leaves"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Leaves"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_pag_ibig,
                ])"
                linkarea="/hrms/setup/pag-ibig"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Pag-Ibig"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_phil_health,
                ])"
                linkarea="/hrms/setup/philhealth"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Philhealth"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_sss,
                ])"
                linkarea="/hrms/setup/sss"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="SSS"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_with_holding_tax,
                ])"
                linkarea="/hrms/setup/wtax"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Withholding Tax"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_settings,
                ])"
                linkarea="/hrms/setup/api-synchronization"
                icon="iconoir:refresh-double"
                single-nav-title="API Synchronization"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_settings,
                ])"
                linkarea="/hrms/setup/settings"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Settings"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_salary_grade,
                ])"
                linkarea="/hrms/setup/salary-grade"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Salary Grade"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.hrms_setup_payrollparticularterms,
                ])"
                linkarea="/hrms/setup/payroll-particular-terms"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Payroll Particular Terms"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    'AdminOnly',
                ])"
                v-show="config.public.BULK_UPLOAD_ENABLED === 'true'"
                linkarea="/hrms/setup/bulk-upload-employee"
                icon="material-symbols:dynamic-form-outline-rounded"
                single-nav-title="Bulk Upload Employee"
            />
        </LayoutNavGroup>
    </LayoutNavModuleGroup>
</template>
