<script setup>
</script>
<template>
    <LayoutNavModuleGroup
        v-if="useCheckAccessibility([
            AccessibilityTypes.PROJECT_MONITORING_GROUP,
        ])"
        title="Project Monitoring"
    >
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECT_MONITORING_DASHBOARD,
            ])"
            linkarea="/project-monitoring"
            icon="ic:baseline-space-dashboard"
            single-nav-title="Projects Dashboard"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECT_MONITORING_MARKETING_GROUP,
            ])"
            linkarea="/project-monitoring/marketing"
            icon="material-symbols:business-center"
            single-nav-title="Marketing"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECT_MONITORING_TSS,
            ])"
            linkarea="/project-monitoring/technical-service"
            icon="material-symbols:linked-services"
            single-nav-title="Technical Service"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECT_MONITORING_SETUP,
            ])"
            icon="iconoir:credit-cards"
            title="Setup"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECT_MONITORING_SETUP,
                ])"
                linkarea="/project-monitoring/setup/positions"
                icon="iconoir:thumbs-up"
                single-nav-title="Position"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECT_MONITORING_SETUP,
                ])"
                linkarea="/project-monitoring/setup/approvals"
                icon="iconoir:thumbs-up"
                single-nav-title="Approvals"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECT_MONITORING_SETUP_SYNCHRONIZATION,
                ])"
                linkarea="/project-monitoring/setup/synchronization"
                icon="iconoir:refresh-double"
                single-nav-title="API Synchronization"
            />
        </LayoutNavGroup>
    </LayoutNavModuleGroup>
</template>
