<script setup>
</script>
<template>
    <LayoutNavModuleGroup
        v-if="useCheckAccessibility([
            AccessibilityTypes.PROJECTMONITORING_GROUP,
        ])"
        title="Project Monitoring"
    >
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECTMONITORING_DASHBOARD,
            ])"
            linkarea="/project-monitoring"
            icon="ic:baseline-space-dashboard"
            single-nav-title="Projects Dashboard"
        />
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECTMONITORING_MARKETING_GROUP,
            ])"
            linkarea="/project-monitoring/marketing"
            icon="material-symbols:business-center"
            single-nav-title="Marketing"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECTMONITORING_SETUP_GROUP,
            ])"
            icon="material-symbols:linked-services"
            title="Technical Service"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECTMONITORING_TSS,
                ])"
                linkarea="/project-monitoring/technical-service/awarded"
                icon="material-symbols:linked-services"
                single-nav-title="Awarded"
            />
        </LayoutNavGroup>
        <LayoutNavSingle
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECTMONITORING_TSS,
            ])"
            linkarea="/project-monitoring/gantt"
            icon="material-symbols:area-chart"
            single-nav-title="Gantt Chart"
        />
        <LayoutNavGroup
            v-if="useCheckAccessibility([
                AccessibilityTypes.PROJECTMONITORING_SETUP_GROUP,
            ])"
            icon="iconoir:credit-cards"
            title="Setup"
        >
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECTMONITORING_SETUP_POSITION,
                ])"
                linkarea="/project-monitoring/setup/positions"
                icon="iconoir:thumbs-up"
                single-nav-title="Position"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECTMONITORING_SETUP_APPROVALS,
                ])"
                linkarea="/project-monitoring/setup/approvals"
                icon="iconoir:thumbs-up"
                single-nav-title="Approvals"
            />
            <LayoutNavSingle
                v-if="useCheckAccessibility([
                    AccessibilityTypes.PROJECTMONITORING_SETUP_SYNCHRONIZATION,
                ])"
                linkarea="/project-monitoring/setup/synchronization"
                icon="iconoir:refresh-double"
                single-nav-title="API Synchronization"
            />
        </LayoutNavGroup>
    </LayoutNavModuleGroup>
</template>
