
# BUILDING FOR CI CD - Static Nuxt.js
name: ProjectSigma_UI Build and Push to CI-Pipeline Branch Manual Trigger

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APPLICATION_NAME: "ProjectSigma_UI"
  GIT_USERNAME: "engtech-projects"
  REPOSITORY_NAME: "ProjectSigma_UI"
  NODE_VERSION: '20.11.1'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "manualbuild ProjectSigma_UI"
  cancel-in-progress: true

jobs:
  build-nuxt-main:
    runs-on: ubuntu-latest
    env:
      # NUXT_APP_BASE_URL: '/ProjectSigma_UI'
      HRMS_API_URL: 'https://projectsigma-hrmsapi.engtechglobalsolutions.com'
      ACCOUNTING_API_URL: 'https://projectsigma-accountingapi.engtechglobalsolutions.com'
      INVENTORY_API_URL: 'https://projectsigma-inventoryapi.engtechglobalsolutions.com'
      PROJECT_API_URL: 'https://projectsigma-projectsapi.engtechglobalsolutions.com'
      BULK_UPLOAD_ENABLED: false
      DEPLOYCHECK: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: corepack enable
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build Nuxt
        run: |
              npm ci;
              npm install;
              npx nuxt build --preset github_pages;
              cd dist
              git config --global user.email "engtechsolutions2020@gmail.com"
              git config --global user.name "EngtechDeploy"
              git init
              git add -A
              git commit -m 'deploy to CI-Manual-Pipeline'
              git push -f https://$GIT_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GIT_USERNAME/$REPOSITORY_NAME.git master:ci-pipe-manual
        shell: bash
